[book]
authors = ["the rustic authors"]
description = "rustic - fast, encrypted, and deduplicated backups"
language = "en"
multilingual = false
src = "src"
title = "rustic dev documentation"

[preprocessor.last-changed]
command = "mdbook-last-changed"
renderer = ["html"]

[output.html]
curly-quotes = true
default-theme = "ayu"
site-url = "/dev-docs/"
git-repository-url = "https://github.com/rustic-rs/dev-docs"
git-repository-icon = "fa-github"
edit-url-template = "https://github.com/rustic-rs/dev-docs/edit/main/{path}"
cname = "rustic.cli.rs"
additional-css = ["./styles/last-changed.css"]

[output.html.fold]
enable = true
level = 0

[output.pandoc]
optional = true
hosted-html = "https://rustic.cli.rs/dev-docs/"

[output.pandoc.profile.pdf]
output-file = "rustic-dev-docs.pdf"
pdf-engine = "lualatex"

[output.pandoc.profile.pdf.variables]
mainfont = "Noto Serif"
sansfont = "Noto Sans"
monofont = "Noto Sans Mono"
mainfontfallback = ["NotoSerifCJKSC:"]
geometry = ["margin=1.25in"]
linkcolor = "blue"
urlcolor = "red"
